apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-service

spec:
  type: NodePort
  selector:
    app: kevin_app2 # ⛳️

  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31232

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rs

spec:
  replicas: 3
  selector: 
    metchLabels:
    app: kevin_app2 # ⛳️

  template:
    # 005.pod.yaml에 있는 값들
    metadata:
      name: kevin_app2 # ⛳️
      namespace: myapp-ns
      labels:
        key: value

    spec:
      containers: # List
        - name: myapp_1
          images: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80

        - name: myapp_2
          images: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 81